version: "2"

# A Docker Compose file for configuration of the development environment

services:
  # load balancer
  lb:
    # The load balancer container. Built from the lb/Dockerfile.
    container_name: lb
    build: lb
    restart: unless-stopped
    networks:
      - backend
    ports:
      - "80:80"

  # app
  app:
    image: ehazlett/docker-demo
    restart: unless-stopped
    networks:
      backend:
        aliases:
          # All app servers be referred to by this alias with the backend network
          - apps
    expose:
      - 8080
    depends_on:
      - lb

networks:
  backend: {}
